#####################
#### AUTOMATIONS ####
#####################

### Time Based ###

# Separate triggers for weekdays and weekends

- alias: "04:40 Basement wake routine"
  trigger:
    platform: time
    at: 04:40
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.early_wake_routine

    
- alias: "05:34 B & J departure routine"
  trigger:
    platform: time
    at: 05:34
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.early_departure_routine

- alias: "5:43 Early Departure Now"
  trigger:
    platform: time
    at: 05:43
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: script.early_departure_now

- alias: "06:59 Wake up boys room"
  trigger:
    platform: time
    at: 06:59
  action:
    service: light.turn_on
    data:
      entity_id: light.boys_color_bulb
      transition: 60
      brightness: 254
      color_temp: 156
- alias: "07:00 Entryway on"
  trigger:
    platform: time
    at: 07:00
  action:
    service: scene.turn_on
    entity_id: scene.entryway_bright
- alias: "07:30 Boys room off"
  trigger:
    platform: time
    at: 07:30
  action:
    service: light.turn_off
    entity_id: light.boys_bedroom
- alias: "08:30 Entryway off" 
  trigger:
    platform: time
    at: 08:30
  action:
    service: light.turn_off
    entity_id: light.entryway


- alias: "17:30 Entryway on" 
  trigger:
    platform: time
    hours: 17
    minutes: 30
  action:
    service: scene.turn_on
    entity_id: scene.entryway_bright

- alias: "19:30 Entryway on" 
  trigger:
    platform: time
    hours: 19
    minutes: 30
  action:
    service: scene.turn_on
    entity_id: scene.entryway_nightlight


- alias: "22:30 dim MB light"
  trigger:
    platform: time
    hours: 22
    minutes: 30
    seconds: 01
  action:
    service: light.turn_on
    entity_id: light.master_bedroom
#    transition: 60
#    brightness: 1
    
- alias: "23:00 turn off entryway light"
  trigger:
    platform: time
    hours: 23
    minutes: 00
  action:
    service: light.turn_off
    entity_id: light.entryway
    

- alias: "23:59 turn MB light off at midnight"
  trigger:
    platform: time
    hours: 23
    minutes: 59
    seconds: 01
  action:
    service: light.turn_off
    entity_id: light.master_bedroom
#    transition: 60

### End Time Based ###




### TURN OFF AFTER DELAY ###

- alias: "TimedOff Laundry room light"
  trigger:
    - platform: state
      entity_id: light.laundry_room
      from: 'off'
      to: 'on'
      for:
        minutes: 30
  action:
    service: light.turn_off
    entity_id: light.laundry_room

- alias: "TimedOff Tool light (shouldn't be left on unless someone is doing stuff near the water softener)"
  trigger:
    - platform: state
      entity_id: switch.tpplug2
      from: 'off'
      to: 'on'
      for:
        minutes: 45
  condition:
    - condition: state
      entity_id: light.basement_bulb_b2
      state: 'on'
  action:
    service: light.turn_off
    entity_id: switch.tpplug2      

- alias: "TimedOff Tool light (no matter what)"
  trigger:
    - platform: state
      entity_id: switch.tpplug2
      from: 'off'
      to: 'on'
      for:
        minutes: 120
  action:
    service: light.turn_off
    entity_id: switch.tpplug2
    
### END Turn Off After Delay ###



### BASEMENT ###

# Family Room #


# Laundry Room #

# Tool Light #



### MAIN FLOOR ###

# Master Bedroom #

    

# Living Room #

### NOTIFICATIONS ###

# EXAMPLES

# - alias: 'Notify that WeMo is turned on'
#   trigger:
#     - platform: state
#       entity_id: switch.wemo_mini
#       from: 'off'
#       to: 'on'
#   action:
#     service: notify.email_annette
#     data:
#       title: 'Test message from our Home Assistant.'
#       message: 'The wemo switch has been turned on.'

- alias: 'Basement on for two hours'
  trigger:
    - platform: state
      entity_id: light.basement_bulb_f1
      to: 'on'
      for: '00:02:00'
  action:
    service: notify.ios_bens_iphone_7
    data:
      message: "Basement left on for 2 hours!"
      data:
        push:
          badge: 3
#          sound: <SOUND FILE HERE>
          category: "alarm" # Needs to match the top level identifier you used in the ios configuration
        action_data: # Anything passed in action_data will get echoed back to Home Assistant.
          entity_id: light.test
          my_custom_data: foo_bar

# Boys Room #

      
      


### HOME ASSISTANT ###

- alias: 'SSL expiry notification'
  trigger:
    platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 14
  action:
    service: notify.notify
    data:
      message: 'Warning - SSL certificate expires in 14 days and has not been automatically renewed'

### TESTING ###


- alias: 'Notify iOS app br_on for 60 min'
  trigger:
    - platform: state
      entity_id: light.boys_color_bulb
      to: 'on'
      for: '00:60:00'
  action:
    service: notify.ios_bens_iphone_7
    data:
      message: "br turned on for 60 min"
      data:
        push:
          badge: 4
#          sound: <SOUND FILE HERE>
          category: "alarm" # Needs to match the top level identifier you used in the ios configuration
        action_data: # Anything passed in action_data will get echoed back to Home Assistant.
          entity_id: light.test
          my_custom_data: foo_bar





## SUN ##

# - alias: "example of sun condition"
#   trigger:
#     - platform: state
#       entity_id: light.laundry_room
#       from: 'off'
#       to: 'on'
#       for:
#         hours: 1
#   condition:
#     - condition: state
#       entity_id: sun.sun
#       state: 'above_horizon'
#   action:
#     service: light.turn_off
#     entity_id: light.laundry_room
