# Time
- platform: yr
- platform: time_date
  display_options:
    - 'time'
    - 'date'
#    - 'date_time'
#    - 'time_date'
#    - 'time_utc'
#    - 'beat'

# SSL Certificate sensor
- platform: command_line
  name: SSL cert expiry
  unit_of_measurement: days
  scan_interval: 10800 # 10800 sec = 3 hours -- check certificate every 3 hours
  command: "ssl-cert-check -b -c /etc/letsencrypt/live/kcannons.duckdns.org/cert.pem | awk '{ print $NF }'"

- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - daily_summary
    - hourly_summary
    - temperature
    - temperature_min
    - temperature_max
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - precip_type
    - precip_intensity
    - precip_probability


